nhl_teams = {
    'ANA': ('Anaheim Ducks', 'Anaheim', 'Pacific', 'Western'),
    'ARI': ('Arizona Coyotes', 'Arizona', 'Central', 'Western'),
    'BOS': ('Boston Bruins', 'Boston', 'Atlantic', 'Eastern'),
    'BUF': ('Buffalo Sabres', 'Buffalo', 'Atlantic', 'Eastern'),
    'CGY': ('Calgary Flames', 'Calgary', 'Pacific', 'Western'),
    'CAR': ('Carolina Hurricanes', 'Raleigh', 'Metropolitan', 'Eastern'),
    'CHI': ('Chicago Blackhawks', 'Chicago', 'Central', 'Western'),
    'COL': ('Colorado Avalanche', 'Denver', 'Central', 'Western'),
    'CBJ': ('Columbus Blue Jackets', 'Columbus', 'Metropolitan', 'Eastern'),
    'DAL': ('Dallas Stars', 'Dallas', 'Central', 'Western'),
    'DET': ('Detroit Red Wings', 'Detroit', 'Atlantic', 'Eastern'),
    'EDM': ('Edmonton Oilers', 'Edmonton', 'Pacific', 'Western'),
    'FLA': ('Florida Panthers', 'Sunrise', 'Atlantic', 'Eastern'),
    'LAK': ('Los Angeles Kings', 'Los Angeles', 'Pacific', 'Western'),
    'MIN': ('Minnesota Wild', 'Saint Paul', 'Central', 'Western'),
    'MTL': ('Montreal Canadiens', 'Montreal', 'Atlantic', 'Eastern'),
    'NSH': ('Nashville Predators', 'Nashville', 'Central', 'Western'),
    'NJD': ('New Jersey Devils', 'Newark', 'Metropolitan', 'Eastern'),
    'NYI': ('New York Islanders', 'Elmont', 'Metropolitan', 'Eastern'),
    'NYR': ('New York Rangers', 'New York', 'Metropolitan', 'Eastern'),
    'OTT': ('Ottawa Senators', 'Ottawa', 'Atlantic', 'Eastern'),
    'PHI': ('Philadelphia Flyers', 'Philadelphia', 'Metropolitan', 'Eastern'),
    'PIT': ('Pittsburgh Penguins', 'Pittsburgh', 'Metropolitan', 'Eastern'),
    'SJS': ('San Jose Sharks', 'San Jose', 'Pacific', 'Western'),
    'SEA': ('Seattle Kraken', 'Seattle', 'Pacific', 'Western'),
    'STL': ('St. Louis Blues', 'St. Louis', 'Central', 'Western'),
    'TBL': ('Tampa Bay Lightning', 'Tampa', 'Atlantic', 'Eastern'),
    'TOR': ('Toronto Maple Leafs', 'Toronto', 'Atlantic', 'Eastern'),
    'UTA': ('Utah Hockey Club', 'Salt Lake City', 'Central', 'Western'),
    'VAN': ('Vancouver Canucks', 'Vancouver', 'Pacific', 'Western'),
    'VGK': ('Vegas Golden Knights', 'Las Vegas', 'Pacific', 'Western'),
    'WSH': ('Washington Capitals', 'Washington', 'Metropolitan', 'Eastern'),
    'WPG': ('Winnipeg Jets', 'Winnipeg', 'Central', 'Western'),
}

divisions = {
    'Atlantic': 'Eastern',
    'Metropolitan': 'Eastern',
    'Central': 'Western',
    'Pacific': 'Western',
}